version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: excel-export
    environment:
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - '3000:3000'
    volumes:
      - /dist
